// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ivsoOs_-uDHJu8AMtg3GBd4jvLc7CRM',
    appId: '1:2760753132:web:dca7dbb20e095431198ac9',
    messagingSenderId: '2760753132',
    projectId: 'blood-donor-connect-cb59f',
    authDomain: 'blood-donor-connect-cb59f.firebaseapp.com',
    storageBucket: 'blood-donor-connect-cb59f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWqcaVGR8MZ-lwAdyI1UODSzuVTTTvsmM',
    appId: '1:2760753132:android:4e9c2d7e3bb5a969198ac9',
    messagingSenderId: '2760753132',
    projectId: 'blood-donor-connect-cb59f',
    storageBucket: 'blood-donor-connect-cb59f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3sIxCo75xqx2NfR6SbS2btppC9t0G-0A',
    appId: '1:2760753132:ios:304fb339c02af7ae198ac9',
    messagingSenderId: '2760753132',
    projectId: 'blood-donor-connect-cb59f',
    storageBucket: 'blood-donor-connect-cb59f.firebasestorage.app',
    iosClientId: '2760753132-7gifgrpjihm7g826psvnnerrp926g99e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonorConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3sIxCo75xqx2NfR6SbS2btppC9t0G-0A',
    appId: '1:2760753132:ios:304fb339c02af7ae198ac9',
    messagingSenderId: '2760753132',
    projectId: 'blood-donor-connect-cb59f',
    storageBucket: 'blood-donor-connect-cb59f.firebasestorage.app',
    iosClientId: '2760753132-7gifgrpjihm7g826psvnnerrp926g99e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonorConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_ivsoOs_-uDHJu8AMtg3GBd4jvLc7CRM',
    appId: '1:2760753132:web:309cf9d2cce8fe5d198ac9',
    messagingSenderId: '2760753132',
    projectId: 'blood-donor-connect-cb59f',
    authDomain: 'blood-donor-connect-cb59f.firebaseapp.com',
    storageBucket: 'blood-donor-connect-cb59f.firebasestorage.app',
  );
}
