import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'providers/auth_provider.dart';
import 'providers/request_provider.dart';
import 'providers/donor_provider.dart';
import 'screens/auth/login_screen.dart';
import 'screens/home/home_screen.dart';
import 'theme/app_theme.dart';

// main() is async because Firebase initialization takes time.
// We must wait for it to complete before the app starts.
void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // required before any async work
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    // MultiProvider wraps the entire app so any widget can access these providers.
    // Think of providers as "global state buckets" the app can read/write.
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => RequestProvider()),
        ChangeNotifierProvider(create: (_) => DonorProvider()),
      ],
      child: const BloodDonorApp(),
    ),
  );
}

class BloodDonorApp extends StatelessWidget {
  const BloodDonorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Blood Donor Connect',
      theme: AppTheme.lightTheme,
      // _AuthGate decides which screen to show based on login status
      home: const _AuthGate(),
    );
  }
}

// _AuthGate is the "router".
// It watches AuthProvider and shows:
//   - A loading spinner while checking if user is already logged in
//   - HomeScreen if logged in
//   - LoginScreen if not logged in
//
// Because it uses context.watch, it AUTOMATICALLY rebuilds when auth state changes.
// This means: after login → HomeScreen appears. After logout → LoginScreen appears.
// You never need to manually navigate on login/logout.
class _AuthGate extends StatefulWidget {
  const _AuthGate();

  @override
  State<_AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<_AuthGate> {
  @override
  void initState() {
    super.initState();
    // Check if a user was already logged in from a previous session
    // (Firebase persists login across app restarts)
    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<AuthProvider>().checkAuthState();
    });
  }

  @override
  Widget build(BuildContext context) {
    final authProvider = context.watch<AuthProvider>();

    switch (authProvider.status) {
      case AuthStatus.initial:
      case AuthStatus.loading:
        // Show a full-screen loading indicator while checking Firebase
        return const Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.bloodtype, size: 60, color: Colors.red),
                SizedBox(height: 20),
                CircularProgressIndicator(color: Colors.red),
              ],
            ),
          ),
        );

      case AuthStatus.authenticated:
        return const HomeScreen();

      case AuthStatus.unauthenticated:
      case AuthStatus.error:
        return const LoginScreen();
    }
  }
}
